FROM node:18.13.0-buster-slim

WORKDIR /app

RUN chown -R node:node /app

COPY --chown=node:node package.json .
COPY --chown=node:node package-lock.json .

USER node

# don't run prepare step with husky
RUN npm pkg delete scripts.prepare

RUN npm i --legacy-peer-deps

EXPOSE 8000

CMD ["npm", "run", "develop"]